Repository SLIIT-PROJECT-THIRD/Research-Project-Management-Tool-Frontend, pull requests merged in 2022-05, with the labels that each got.

#2 implemented env and necessary files to this commit
  .env
  package-lock.json
  package.json
  src/App.js
  src/Home.js
  src/assets/student.css
  src/pages/student/register.js
  src/pages/student/sample.md
Labels: feature

#3 .env file comment
  .gitignore
Labels: documentation

#4 Student register and Login forms are crerated
  package-lock.json
  package.json
  src/App.js
  src/Home.js
  src/assets/student.css
  src/pages/student/register.js
Labels: enhancement

#7 feat(usermanagement): Branch creation
  package-lock.json
Labels: feature

#9 Implemented the Admin frontend Login and Registration
  package-lock.json
  package.json
  src/App.js
  src/SessionManager.js
  src/assets/admin/Login.css
  src/pages/admin/dashboard.js
  src/pages/admin/login.js
  src/pages/admin/register.js
Labels: fix

#10 Updates for Heroku Docker Deployment
  package-lock.json
  package.json
  src/Home.js
  src/assets/student/student.css
  src/pages/student/register.js
Labels: enhancement, fix

#11 updated
  Dockerfile
Labels: fix

#13 updated with fixing
  package-lock.json
  package.json
  src/Home.js
Labels: fix

#14 env API updated
  .env
Labels: enhancement, feature

#16 Feat/student register and login
  .env
  src/Home.js
  src/pages/student/register.js
  src/pages/student/sample.md
Labels: enhancement, feature, fix
