Repository SLIIT-PROJECT-THIRD/Research-Project-Management-Tool-Frontend, pull requests merged in 2022-06, with the labels that each got.

#25 Student register and group
  src/App.js
  src/assets/student/group-details.css
  src/assets/student/student.css
  src/components/student/Navbar.js
  src/pages/student/dashboard.js
  src/pages/student/project-group/groupRegister.js
  src/pages/student/project-group/index.js
  src/pages/student/register.js
  src/services/SessionManager.js
Labels: enhancement

#26 Feat/user management
  package-lock.json
  package.json
  src/assets/admin/avatar7.png
  src/components/Admin/SubTypeTableRow.js
  src/pages/admin/Navbar.js
  src/pages/admin/Userprofile.js
Labels: enhancement, fix

#27 Student group details view
  src/pages/student/project-group/groupRegister.js
  src/pages/student/project-group/index.js
Labels: enhancement, feature

#29 Feat/user management
  src/App.js
  src/pages/admin/Userprofile.js
Labels: fix

#31 updates to staff
  src/pages/Staff/register.js
Labels: fix

#32 Student group details view
  package-lock.json
  src/App.js
  src/components/student/Navbar.js
  src/pages/student/project-group/groupRegister.js
  src/pages/student/project-group/index.js
  src/pages/student/supervisor/index.js
  src/pages/student/supervisor/requestSupervisor.js
Labels: enhancement, feature

#33 Implemented Admin user profile update
  src/App.js
  src/pages/admin/Userprofile.js
  src/pages/admin/updateAdmin.js
Labels: enhancement, fix

#34 Login response alerts added to Admin Login
  src/pages/admin/login.js
Labels: feature

#35 Student group details view
  src/components/student/Navbar.js
  src/pages/student/project-group/index.js
  src/pages/student/supervisor/index.js
  src/services/SessionManager.js
Labels: enhancement, feature

#36 Student group details view
  src/App.js
  src/assets/student/scrollable-div.css
  src/pages/admin/Sidebar.js
  src/pages/student/admin/AllStudents.js
Labels: enhancement, feature, fix

#37 Student group details view
  src/App.js
  src/pages/student/admin/AllStudents.js
  src/pages/student/admin/UpdateGroup.js
  src/pages/student/admin/UpdateStudent.js
  src/pages/student/project-group/groupRegister.js
Labels: enhancement, feature

#38 Student group details view
  src/App.js
  src/pages/admin/Sidebar.js
  src/pages/student/admin/AllGroups.js
  src/pages/student/admin/AllStudents.js
  src/pages/student/admin/UpdateGroup.js
  src/pages/student/admin/UpdateStudent.js
  src/pages/student/dashboard.js
  src/pages/student/project-group/groupRegister.js
  src/pages/student/project-group/index.js
  src/pages/student/register.js
  src/pages/student/supervisor/index.js
  src/pages/student/supervisor/requestSupervisor.js
  src/services/PrivateRoutes.js
  src/services/SessionManager.js
Labels: enhancement, feature, fix

#41 Logout session
  .env
  src/components/student/Navbar.js
  src/pages/student/supervisor/index.js
  src/services/SessionManager.js
Labels: enhancement, feature

#46 Updates to admin user management
  package-lock.json
  src/App.js
  src/pages/Staff/updateStaff.js
  src/pages/admin/Sidebar.js
  src/pages/admin/dashboard.js
  src/pages/admin/editProfile.js
Labels: enhancement

#47 Logout session
  src/App.js
  src/SessionManager.js
  src/pages/student/admin/AllGroups.js
  src/pages/student/admin/AllStudents.js
  src/pages/student/register.js
  src/services/PrivateRouteAdmin.js
  src/services/PrivateRoutes.js
  src/services/SessionManager.js
Labels: enhancement, feature, fix

#48 Implemented the submission detail update
  src/App.js
  src/components/Admin/SubTypeTableRow.js
  src/components/Admin/update_subtype.js
Labels: enhancement

#49 Updates to Side bar
  src/pages/admin/Sidebar.js
Labels: enhancement

#52 Feat/user management
  Test/checkNullUserLogin.js
  Test/onSubmit.test.js
  src/pages/Staff/dashboard.js
  src/pages/admin/dashboard.js
Labels: feature, fix
